# Generated by Django 5.2 on 2025-08-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_date_subscribed_newslettersubscriber_subscribed_at'),
    ]

    operations = [
    ]
